"""add learning reviews for runtime hitl

Revision ID: 14dde413b083
Revises: d1aa888437a3
Create Date: 2026-09-05 21:12:47.473952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dde413b083'
down_revision: Union[str, Sequence[str], None] = 'd1aa888437a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_reference_id', sa.String(length=100), nullable=True),
    sa.Column('question_or_activity', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('retrieved_sources', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('reason_for_escalation', sa.String(length=255), nullable=False),
    sa.Column('student_attempts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_reviews_activity_reference_id'), 'learning_reviews', ['activity_reference_id'], unique=False)
    op.create_index(op.f('ix_learning_reviews_activity_type'), 'learning_reviews', ['activity_type'], unique=False)
    op.create_index(op.f('ix_learning_reviews_reviewed_by'), 'learning_reviews', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_learning_reviews_status'), 'learning_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_learning_reviews_student_id'), 'learning_reviews', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_reviews_student_id'), table_name='learning_reviews')
    op.drop_index(op.f('ix_learning_reviews_status'), table_name='learning_reviews')
    op.drop_index(op.f('ix_learning_reviews_reviewed_by'), table_name='learning_reviews')
    op.drop_index(op.f('ix_learning_reviews_activity_type'), table_name='learning_reviews')
    op.drop_index(op.f('ix_learning_reviews_activity_reference_id'), table_name='learning_reviews')
    op.drop_table('learning_reviews')
    # ### end Alembic commands ###
