"""add lesson assessment attempts

Revision ID: 1609015a7c88
Revises: e8c7679f9122
Create Date: 2026-10-01 00:00:26.836688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1609015a7c88'
down_revision: Union[str, Sequence[str], None] = 'e8c7679f9122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_assessment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('curriculum_id', sa.String(length=50), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_assessment_attempts_curriculum_id'), 'lesson_assessment_attempts', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_lesson_assessment_attempts_lesson_id'), 'lesson_assessment_attempts', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_assessment_attempts_user_id'), 'lesson_assessment_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_assessment_attempts_user_id'), table_name='lesson_assessment_attempts')
    op.drop_index(op.f('ix_lesson_assessment_attempts_lesson_id'), table_name='lesson_assessment_attempts')
    op.drop_index(op.f('ix_lesson_assessment_attempts_curriculum_id'), table_name='lesson_assessment_attempts')
    op.drop_table('lesson_assessment_attempts')
    # ### end Alembic commands ###
