"""add isl practice attempts

Revision ID: d1aa888437a3
Revises: 15ed025ee8f4
Create Date: 2026-09-04 23:45:27.087588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aa888437a3'
down_revision: Union[str, Sequence[str], None] = '15ed025ee8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isl_practice_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_letter', sa.String(length=1), nullable=False),
    sa.Column('predicted_letter', sa.String(length=1), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isl_practice_attempts_user_id'), 'isl_practice_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_isl_practice_attempts_user_id'), table_name='isl_practice_attempts')
    op.drop_table('isl_practice_attempts')
    # ### end Alembic commands ###
