"""add accessibility profile to users

Revision ID: e8c7679f9122
Revises: 14dde413b083
Create Date: 2026-09-23 11:27:03.084486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c7679f9122'
down_revision: Union[str, Sequence[str], None] = '14dde413b083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessibility_profile', sa.String(length=30), server_default='standard', nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=30), server_default='english', nullable=False))
    op.add_column('users', sa.Column('isl_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('captions_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'captions_enabled')
    op.drop_column('users', 'isl_enabled')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'accessibility_profile')
    # ### end Alembic commands ###
